apiVersion: v1
kind: ConfigMap
metadata:
  name: restapi-config
  namespace: {{ .Values.namespace }}

data:
  DATABASE_URL: "postgresql://postgres:password@postgresdb-service:5432/students"
  PORT: "5000"