events {}

http {

    upstream studentapi {
        server student-api-1:5000;
        server student-api-2:5000;  # we actually don't need to use 8081/8082 here coz nginx can directly access the internal expose port of the application i.e, 5000 [where the container listens] coz nginx and the containers are in the same network/place so they can communcate internally as well
    }

    server {
        listen 8080;

        location / {
            proxy_pass http://studentapi;
        }
    }
}