name: sre-bootcamp-cicd

on:
  workflow_dispatch:
  push:
    branches:
      - "main"
    paths:
      - "REST_API/*"

env:
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

jobs:
  build-and-push :
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v6.0.2
      
      - name: Setup Python
        uses: actions/setup-python@v6.2.0
        with: 
          python-version: "3.10"
        
      - name: Install Dependencies
        run: pip install -r ./REST_API/requirements.txt

      - name: Python flake8 Lint
        uses: py-actions/flake8@v2.3.0

      - name: Code Checks
        run: make codechecks
      
      - name: Testing
        run: make tests
        env:
          DATABASE_URL: "sqlite:///test.db"  # THIS IS ADDED JUST TO PASS THE DB CONNECTION URL CHECK AVAILABILITY TEST BY PYTEST, ADDED THIS COZ WE ARE GOING TO USE THAT REAL URL CONNECTION OF DB TO MAIN CONTAINER IN K8S, AND WE WILL BE SAFE FROM USING THE ENV VALUES HERE

      - name: docker build
        run: make build

      - name: docker login
        run: make docker-login

      - name: Push
        run: make push