name: sre-bootcamp-cicd

on:
  workflow_dispatch:
  push:
    branches:
      - "main"
    paths:
      - "REST_API/*"

env:
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

jobs:
  build-and-push :
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v6.0.2
      
      - name: Setup Python
        uses: actions/setup-python@v6.2.0
        with: 
          python-version: "3.10"
        
      - name: Install Dependencies
        run: pip install -r requirements.txt

      - name: Code Checks
        run: make codechecks
      
      - name: Testing
        run: make tests

      - name: docker build
        run: make build

      - name: docker login
        run: make docker-login

      - name: Push
        run: make push
        

        
