name: sre-bootcamp-cicd

on:
  workflow_dispatch:
  push:
    branches:
      - "main"
    paths:
      - "REST_API/*"

env:
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

jobs:

  build-n-push :
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v6.0.2
      
      - name: Setup Python
        uses: actions/setup-python@v6.2.0
        with: 
          python-version: "3.10"
        
      - name: Install Dependencies
        run: pip install -r ./REST_API/requirements.txt

      - name: Python flake8 Lint
        uses: py-actions/flake8@v2.3.0

      - name: Code Checks
        run: make codechecks
      
      - name: Testing
        run: make tests
        env:
          DATABASE_URL: "sqlite:///test.db"  
# Because during CI tests, PostgreSQL container is not running,
# So we use: sqlite:///test.db, which creates a small local test database automatically

      - name: docker build
        run: make build
        env:
          TAG: ${GITHUB_SHA::7}

      - name: docker login
        run: make docker-login

      - name: Push
        run: make push
        env:
          TAG: ${GITHUB_SHA::7}



  deploy :
    needs: build-n-push
    runs-on: self-hosted
    steps:

      - name: Checkout code
        uses: actions/checkout@v6.0.2
        
      - name: updating the "image tag" in values of helm
        run: |
          sed -i 's/tag:.*/tag: "'"${GITHUB_SHA::7}"'"/g' helm/student-api/values.yaml
          
      - name: git commit changes
        run: |
          git add helm/student-api/templates/values.yaml
          git commit -m "image-tag updated"
          git push origin/main